services:
  indic-translate-server:
    image: slabstech/indic_translate_server_12_6
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - 7860:7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]