FROM pytorch/pytorch:2.6.0-cuda12.6-cudnn9-devel
# hadolint ignore=DL3008,DL3015,DL4006
RUN apt-get update && \
    apt-get install -y git curl software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y python3.12 python3-distutils python3-dev && \
    curl -sS https://bootstrap.pypa.io/get-pip.py | python3.12 && \
    apt-get install -y build-essential gcc g++ && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /root/indic_translate_server
RUN apt-get update && \
    apt-get install -y python3.12-venv
RUN export CC=/usr/bin/gcc
RUN export CXX=/usr/bin/g++
WORKDIR /root/indic_translate_server
COPY ./requirements.txt .
RUN pip3.12 install --no-cache-dir -r requirements.txt

COPY ./indic_translate_server ./indic_translate_server
CMD ["uvicorn", "indic_translate_server.translate_api:app"]
ENV UVICORN_HOST=0.0.0.0
ENV UVICORN_PORT=8000